### ISSUE TITLE
Plan Secure Storage options for keys and data

### ISSUE THREAD

**Issue by rodolfomiranda** [roots-id/rootswallet#11]
See https://github.com/roots-id/rootswallet/wiki/Roots-Wallet-Implementation-Proposal#layer-1-utilities-and-ledger-interface

**Comment by 2byrds** [comment]
i'm playing with adding an expo securestore prototype to our test page.  https://docs.expo.dev/versions/latest/sdk/securestore/.  it's a common way to store encrypted passwords, keys, values.  it is cross platform for mobile, but not for web.  seems pretty straight forward.  Size limit for a value is 2048 bytes... roughly 340 UTF-8 characters

**Comment by rodolfomiranda** [comment]
it's a good place to store main seeds. Probably, it supports automatic backup in google and apple clouds, so they can be restored if change device or delete app.

**Comment by 2byrds** [comment]
expo secure store is a reasonable start for Fund 7.
iOS: Values are stored using the [keychain services](https://developer.apple.com/documentation/security/keychain_services) as kSecClassGenericPassword. iOS has the additional option of being able to set the value's kSecAttrAccessible attribute, which controls when the value is available to be fetched.
Android: Values are stored in [SharedPreferences](https://developer.android.com/training/basics/data-storage/shared-preferences.html), encrypted with [Android's Keystore system](https://developer.android.com/training/articles/keystore.html).
