### ISSUE TITLE
Camera on emulator

### ISSUE THREAD

**Issue by 2byrds** [roots-id/rootswallet#113]
@rodolfomiranda was able to use this guide to use his laptop camera for his emulator to scan a QR code:
https://stackoverflow.com/questions/13818389/android-emulator-camera-custom-image

But when I use the camera, i get a blank screen.  likely at some point i set the permissions to not allow the emulator to have access to the camera.  I'm on MacOS w/ m1 (arm). I'm not sure how to reset the access permissions.

**Comment by 2byrds** [comment]
Trying things from here:
https://youtrack.jetbrains.com/issue/IDEA-219288
so far `tccutil reset Camera` did not help

**Comment by rodolfomiranda** [comment]
In Mac settings, security and privacy, and in the camera option I have  permits for Android Studio. Do you?

**Comment by 2byrds** [comment]
i've been using IntelliJ to launch my emulators and don't get a prompt to give camera access.
but i had the same problem previously in AndroidStudio when i was using that.
now that i reset my camera permissions, no apps are listed and i was hoping i'd get a permission prompt.
no luck on that.
Some other diagnostics i've tried include from the command line `emulator Pixel_5_API_30 -webcam-list` which gives me an empty response.  i believe if i could at least get command line camera access working then i could work from there..... i'll try to find something about that

**Comment by 2byrds** [comment]
a semi-useful side note.... apple xcode simulator has no camera access... but some online knowledge says that's true for everyone.... simulator is not an emulator.... https://developer.apple.com/forums/thread/661493
but android emulator should work. just note we might not be able to do it with ios versions in the future.

**Comment by 2byrds** [comment]
fyi android emulator command line docs https://developer.android.com/studio/run/emulator-commandline

**Comment by 2byrds** [comment]
No luck for virtual scene nor emulated camera.  i'm pretty sure it is an issue with my env settings.  i'll try a clean environment at some point.
