### ISSUE TITLE
Select a DIDComm implementation that works with iPhone

### ISSUE THREAD

**Issue by 2byrds** [roots-id/rootswallet#124]
What choices of DIDComm implementations do we have that work on iPhone?

**Comment by rodolfomiranda** [comment]
I see two path:
1. add sicpa swift wrapper of didcom rust as a native library
2. use a javascript library that can be full js/ts library or a rust wrapper on wasm (if it works for react-native)

**Comment by 2byrds** [comment]
We used prism DIDComm.  And there is a new task for this: https://github.com/roots-id/roots-react-native/issues/47
