### ISSUE TITLE
Tiny URL for Mediator didn't work when scanned

### ISSUE THREAD

**Issue by 2byrds** [roots-id/rootswallet#128]

**Comment by rodolfomiranda** [comment]
which QR code did you scanned?

**Comment by 2byrds** [comment]
@rodolfomiranda the tiny url here https://github.com/roots-id/didcomm-mediator

**Comment by rodolfomiranda** [comment]
tray again. Short URL was expired (they have a mandatory expiration)

**Comment by 2byrds** [comment]
worked great!
