### ISSUE TITLE
DID method operations for did prism: Create/Publish

### ISSUE THREAD

**Issue by 2byrds** [roots-id/rootswallet#15]
See https://github.com/roots-id/rootswallet/wiki/Roots-Wallet-Implementation-Proposal#layer-1-utilities-and-ledger-interface

**Comment by Essbante** [comment]
We will only need prism did create (at least for our first release), the issuer/verifier role will be covered by WAL

**Comment by 2byrds** [comment]
thank you WAL :)

**Comment by 2byrds** [comment]
We have successfully created and published a DID as well as a credential, in this demo.
https://github.com/roots-id/rootschat/commit/d5a7be5d9d1b3550ed97abdd68120093fc496acb
It uses Wal-lib.
