### ISSUE TITLE
DID method operations for did peer: Create, Update, Resolve, and Deactivate

### ISSUE THREAD

**Issue by 2byrds** [roots-id/rootswallet#16]
See https://github.com/roots-id/rootswallet/wiki/Roots-Wallet-Implementation-Proposal#layer-1-utilities-and-ledger-interface

**Comment by rodolfomiranda** [comment]
So far, I only found one implementation, and it's in python:
https://github.com/evernym/pypeerdid

**Comment by rodolfomiranda** [comment]
great discovery by @Essbante :

 https://github.com/sicpa-dlab/peer-did-jvm
