### ISSUE TITLE
Coding best practices

### ISSUE THREAD

**Issue by rodolfomiranda** [roots-id/rootswallet#3]
I open this issue to create a list of coding best practices that we can discuss and publish afterwards:

1. all UI texts must be localized i18n
2. avoid dependency to non-mature and/or non well adopted external libraries
3.

**Comment by rodolfomiranda** [comment]
should we move that to the wiki?

**Comment by 2byrds** [comment]
> should we move that to the wiki?

it is currently in the README https://github.com/roots-id/rootswallet#readme, but maybe it is better in the wiki

**Comment by 2byrds** [comment]
wiki page created.
https://github.com/roots-id/rootswallet/wiki/Contributor-Recommendations
