### ISSUE TITLE
Create / Gather graphics elements for Wallet App

### ISSUE THREAD

**Issue by ButchClark** [roots-id/rootswallet#34]
We will need several graphics, layout, and color bits to make a consistent looking app.  These elements include:

#Components Needed
For guidance, refer to this issue:
- [x] #10
- [x ] https://github.com/roots-id/rootswallet/issues/10
- [ ] favicon :tada:
- [ ] background default color
- [ ] highlight color
- [ ] Font style
- [ ] Font color - default / highlighted / greyed out
- [ ] splash screen image
- [ ] background image
- [ ] etc

**Comment by rodolfomiranda** [comment]
do we need to hire a designer?

**Comment by 2byrds** [comment]
@Essbante  has the connections.  Happy to send some Ada to cover it.

**Comment by rodolfomiranda** [comment]
sure!

**Comment by 2byrds** [comment]
same elements are here https://www.rootswallet.com/.  so either we use what we already have or update website, youtube, github, etc

**Comment by 2byrds** [comment]
current theme pallet
data-color="#e69138"
data-color="#b0bf93" 
data-color="#000000"
data-color="#1c1c1c" 
data-color="#2f2f2f" 
data-color="#f9f9f9"

**Comment by 2byrds** [comment]
font is montserrat 12
favicon, banner, and background images are from our branding images
