### ISSUE TITLE
DID method operations for did prism: Update, Deactivate

### ISSUE THREAD

**Issue by 2byrds** [roots-id/rootswallet#41]
These operations are left to do, since we've successfully created/published DIDs and credentials in this demo
https://github.com/roots-id/rootschat/commit/d5a7be5d9d1b3550ed97abdd68120093fc496acb

**Comment by 2byrds** [comment]
@Essbante can you provide some thoughts/timeline for updating/deactivating a did:prism DID?

**Comment by Essbante** [comment]
@2byrds Update has always been part of wal-lib v1.x It goes as addKey and revokeKey. Those are the only "updates" supported by PRISM. The deactivate operation was added with PRISM v1.4 I can add it to wal-lib 1.x if you want.

**Comment by 2byrds** [comment]
no rush.  it was something we've had on our list but no pressing need.  and maybe i'll shift to JS version of the lib before i ever need it.

**Comment by 2byrds** [comment]
this will wait until Atala 2.0 and corresponding wal-lib update (if we will continue with wal-lib)

**Comment by 2byrds** [comment]
will be in roots-prism
