### ISSUE TITLE
First Install

### ISSUE THREAD

**Issue by rodolfomiranda** [roots-id/rootswallet#5]
**The initial template was created as follows:**

If first time with React Native, install expo cli:
`yarn global add expo-cli`

Generate blank TypeScrip template:
`expo init rootswallet`

Generate Android and iOS code (use com.rootswallet as Android Package and iOS Bundle Identifier):
```
cd rootswallet
yarn eject
```

Then I created  PrismModule.kt, RootsWallet.java loaded in MainApplication.java. Add kotlin and prism code in build.gradle.

**How to build and run:**
If first time with React Native, install expo cli:
`yarn global add expo-cli`

Install dependencies:
`yarn install`

In my MAC I had to:
`export ANDROID_SDK_ROOT=/Users/rodolfo/Library/Android/sdk`

Export Prism SDK password:
`export PRISM_SDK_PASSWORD=ghp_2CTxxxxxxxxxxx`

Install Android Studio, and open Simulator from ADV Manager

Build and run:
`yarn android`

See app launching in simulator, click to generate DID, and see generated DID in log

**Comment by Essbante** [comment]
Only difference on the windows setup, I had to install:

`yarn global add expo`

**Comment by 2byrds** [comment]
All team members have completed a first install
