### ISSUE TITLE
Peer DiD priviledge model

### ISSUE THREAD

**Issue by 2byrds** [roots-id/rootswallet#8]
From https://youtu.be/d-5MmLLd3xY
Register
Route
Authcrypt
Plaintext
Oblige
Key_admin
Se_admin
Rule_admin

**Comment by rodolfomiranda** [comment]
and the jvm version:
https://github.com/sicpa-dlab/peer-did-jvm

**Comment by 2byrds** [comment]
@rodolfomiranda will generate specific tickets as our DIDComm implementation did:peer usage continues progress.
